# Repaclace this with your custom ci image, if needed
image: xoelabs/dockery-odoo:ci
cache:
  untracked: true
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
stages:
  - Pre-Build
  - Build
  - Test
  - Stage
  - Release
  - Deploy
before_script:
- docker version
- docker-compose version
- kubectl version --client
- terraform version
- consul version
- etcdctl version
# Set the repo's environment
- export $(egrep -v '^#' .env | xargs)
- chmod -R +x ./scripts

Update-Project-Image:
  stage: Pre-Build
  only: [branches]
  # Run this job on runners with docker-socket binding
  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
  tags: [image-builder]
  except: ['/^HOTFIX-.*$/']
  script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./scripts/ci-build-main.sh

Update-Tester:
  stage: Build
  only: [branches]
  # Run this job on runners with docker-socket binding
  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
  tags: [image-builder]
  except: ['/^HOTFIX-.*$/']
  script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./scripts/ci-build-helper.sh tester

Update-Migrator:
  stage: Build
  only: [tags]
  # Run this job on runners with docker-socket binding
  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
  tags: [image-builder]
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./scripts/ci-build-helper.sh migrator

Test-Diff:
  # Make sure $CI_REGISTRY_IMAGE is the same as $IMAGE
  image: "${CI_REGISTRY_IMAGE}:tester"
  only: [branches]
  except: ['/^HOTFIX-.*$/']
  stage: Test
  variables:
    # Database connection
    PGHOST: YOURHOST
    PGPORT: 5432
    PGUSER: YOURUSER
    PGPASSWORD: YOUERPASSWORD # Prefer using more secure gitlab ci variables
    # Modules configuration
    BASEBRANCH: origin/master
    INCLUDE: YOUR_INTEGRATION_TEST_MODULE
    # Helper variables
    ODOO_BASEPATH: /testbed
    DB_SLUG: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  before_script:
    - echo "... mute global before script."
  script:
    - prepare-testbed
    # Symlink vendored modules
    # - ln -s "${CI_PROJECT_DIR}/vendor/oca/job-queue"       "${ODOO_BASEPATH}/addons/010"
    - exec-test-on-diff

Migrate-Staged-DBs:
  # Make sure $CI_REGISTRY_IMAGE is the same as $IMAGE
  image:
    name: "${CI_REGISTRY_IMAGE}:migrator"
    entrypoint: [""]
  only: [tags]
  stage: Stage
  variables:
    STAGED_DBS: "vspace separated list of existing dbs to stage migration"
    # Database connection
    MARABUNTA_DB_HOST: YOURHOST
    MARABUNTA_DB_PORT: 5432
    MARABUNTA_DB_USER: YOURUSER
    MARABUNTA_DB_PASSWORD: YOURPASSWORD
  before_script:
    - echo "... mute global before script."
  script:
    - |
        for db in ${STAGED_DBS}; do
            /entrypoint-migrator.sh -f ./.marabunta.yml --database "${db}"
        done

Release-Review-Image:
  stage: Release
  only: [branches]
  # Run this job on runners with docker-socket binding
  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
  tags: [image-builder]
  except: ['/^HOTFIX-.*$/']
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./scripts/ci-build-main.sh "${CI_COMMIT_REF_SLUG}"

Release-Project-Image:
  stage: Release
  only: [tags]
  # Run this job on runners with docker-socket binding
  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
  tags: [image-builder]
  allow_failure: false
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./scripts/ci-build-main.sh "${CI_COMMIT_TAG}"

Start-Review-App:
  stage: Deploy
  only: [branches]  # This is a Review-Deployment
  variables:
    REVIEW_DOMAIN: example.com
    DB_SLUG: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG  # We re-use the testing environment
  script:
    - echo "Deploy review app"
    # Change the name of the deployment
    - kubectl patch -f ./.review-app.yaml --local -p='{"metadata":{"name":"${DB_SLUG}"}}'
    # Use the right image
    - kubectl patch -f ./.review-app.yaml --local -p='[{"op":"replace","path":"/spec/tracks/0/image/tag","value":"${CI_COMMIT_TAG}"}]'
    # Use the correct postgres credentials
    # TODO: Maybe root password not needed if a shared review-app DB namespace is used.
    - kubectl patch -f ./.review-app.yaml --local -p='{"pgNsSpec":{"user":"${PGUSER}"}, "password":"${PGPASSWORD}", "pgCluster":{"user":"${PGROOTUSER}","password":"${PGROOTPASSWORD}"}}}'
    # .. The rest can be safely version controlled within the .review-app.yaml
    - kubectl create -f ./.review-app.yaml
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.${REVIEW_DOMAIN}/web/login?db=${DB_SLUG}&login=admin&redirect=/web?debug=1
    on_stop: Stop-Review-App

Stop-Review-App:
  stage: Deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app"
    # Change the name of the deployment
    - kubectl patch -f ./.review-app.yaml --local -p='{"metadata":{"name":"${DB_SLUG}"}}'
    - kubectl delete -f ./.review-app.yaml
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

# CI GIT & Component Configuration
variables:
  GIT_DEPTH: '10'
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: 'recursive'
  GIT_SSL_NO_VERIFY: "true"
