exclude: 'vendor/*'
repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 18.8.0", "flake8-per-file-ignores"]
        language_version: python3.6
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.8.0
    hooks:
    - id: pyupgrade
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.3.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v1.8.4
    hooks:
    -   id: pylint
        language_version: python3.6
        entry: pylint -d no-utf8-coding-comment -d manifest-required-author -d missing-readme -d redundant-modulename-xml
        additional_dependencies: [
          'astroid==1.6.3',
          'pylint-plugin-utils==0.2.4',
          'docutils==0.14',
          'lxml>=2.3.2',
          'Pygments==2.2',
          'restructuredtext_lint==1.1',
          'isort==4.3.4',
          'whichcraft',
          'rfc3986',
          'six',
          'pylint-odoo==2.0.2'
        ]
