version: '3.4'


# x-* key is ignored by docker-compose
x-odoo:
  &add-additional-volumes
  volumes:
  # Put additional volumes here
  - ./.gitignore:/.gitignore:ro

services:
  odoo:
    << : *add-additional-volumes
  tests:
    << : *add-additional-volumes
  shell:
    << : *add-additional-volumes
  migrate:
    << : *add-additional-volumes
  init:
    << : *add-additional-volumes
  load:
    << : *add-additional-volumes
  # translate:
  #   << : *add-additional-volumes
