version: '3.4'


# x-* key is ignored by docker-compose
x-odoo:
  &add-additional-volumes
  volumes:
  # Put additional volumes here
  - ./.gitignore:/.gitignore:ro

services:
  odoo:
    << : *add-additional-volumes
  odoo-redis:
    << : *add-additional-volumes
  dodoo:
    << : *add-additional-volumes
  scaffold:
    << : *add-additional-volumes
  tests:
    << : *add-additional-volumes
