version: '3.4'


x-odoo:
  &default-odoo
  tty: true
  image: "${IMAGE}:edge-${ODOO_VERSION}-devops"
  # ports: ['80:8069', '8072:8072']
  # Comment on layered projects
  environment:
    - ODOO_CMD=/opt/odoo/vendor/odoo/cc/odoo-bin
    - ODOO_FRM=/opt/odoo/vendor/odoo/cc
  secrets:
    - source: adminpwd
      target: /run/secrets/adminpwd
  volumes:
  # Named Data volumes
  - odoo-data:/var/lib/odoo-persist
  - odoo-backup:/var/lib/odoo-backup
  - odoo-testlogs:/var/lib/odoo-testlogs
  - odoo-dodoo-loader:/var/lib/dodoo-loader
  # Host paths (config)
  - ./cfg.d:/opt/odoo/cfg.d:ro  # ${ODOO_RC}
  # Host paths (source)
  - ./src:/opt/odoo/src:ro  # ${ODOO_SRC}
  - ./vendor:/opt/odoo/vendor:ro  # ${ODOO_VENDOR}
  # Current migration instructions
  - ./migration.yaml:/opt/odoo/migration.yaml:ro  # ${ODOO_MIG}
  - ./migration.d:/opt/odoo/migration.d:ro  # ${ODOO_MIG_DIR}

secrets:
  adminpwd: {file: .adminpwd}
volumes:
  odoo-data: {driver: local}
  odoo-backup: {driver: local}
  odoo-testlogs: {driver: local}
  odoo-dodoo-loader: {driver: local}
  psql: {driver: local}
networks:
  default: {internal: true}
  public: null
services:
  db:
    environment: [POSTGRES_USER=odoo, POSTGRES_PASSWORD=odoo, POSTGRES_DB=postgres]
    image: postgres:alpine
    ports: ['5433:5432']
    volumes: ['psql:/var/lib/postgresql/data']
  # http://filebrowser.localhost
  filebrowser:
    command: [--noauth]
    image: filebrowser/filebrowser
    volumes: ['odoo-data:/srv/data', 'odoo-backup:/srv/backup', 'odoo-testlogs:/srv/testlogs',
      'odoo-dodoo-loader:/srv/etl']
  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    networks: {default: null, public: null}
    ports: ['80:80']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']
  redis: {image: 'redis:5.0-alpine'}
  # http://mail.localhost
  smtpfake: {image: mailhog/mailhog}
  # http://wdb.localhost
  wdb:
    image: kozea/wdb:3.2.5
    ports: ['1984:1984']

  # http://odoo.localhost
  odoo:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['db', 'wdb', 'proxy', 'smtpfake']
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_SOCKET_PORT=19840
      - WDB_WEB_SERVER=wdb.localhost
      - WDB_WEB_PORT=80

  # http://odoo.localhost
  odoo-redis:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh', 'odoo-redis', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    command: []
    depends_on: ['db', 'wdb', 'proxy', 'smtpfake', 'redis']

# ========================

  dodoo:
    << : *default-odoo
    depends_on: ['db', 'wdb']
    entrypoint: ['/entrypoint.sh', 'dodoo']
    command: []

# ------------------------

  scaffold:
    << : *default-odoo
    user: "${COMPOSE_IMPERSONATION}"
    entrypoint: ['/entrypoint.sh', 'scaffold']
    command: []
    volumes:
    - ./src:/opt/odoo/src

# ------------------------

  apply-patches:
    tty: true
    image: "${IMAGE}:edge-${ODOO_VERSION}-devops"
    volumes:
    - ./vendor:/opt/odoo/vendor
    user: "${COMPOSE_IMPERSONATION}"
    entrypoint: ['/patches']
    command: []
    networks: [public]

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['db', 'wdb']
    entrypoint: ['/entrypoint.sh', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--without-demo=False', '--stop-after-init', '--logfile', '/var/lib/odoo-testlogs/']
    command: []
