version: '3.4'


x-odoo:
  &default-odoo
  tty: true  # Do not avoid json logging
  image: "${IMAGE}:devops-${ODOO_VERSION}"
  ports: ['80:8069', '8072:8072']
  secrets:
    - source: adminpwd
      target: /run/secrets/adminpwd
  volumes:
  # Named Data volumes
  - odoo-data:/var/lib/odoo-persist
  - odoo-backup:/var/lib/odoo-backup
  - odoo-testlogs:/var/lib/odoo-testlogs
  - odoo-dodoo-loader:/dodoo-loader
  # Host paths (config)
  - .cfg-default.ini:/opt/odoo/cfg.d/01-default:ro
  - .cfg-custom.ini:/opt/odoo/cfg.d/02-custom:ro
  # Host paths (source)
  - ./src:/opt/odoo/src:ro
  - ./vendor:/opt/odoo/vendor:ro
  # Current migration instructions
  - .migration.yml:/opt/odoo/.migration.yml:ro

secrets:
  adminpwd:
    file: .adminpwd

volumes:
  odoo-data: {driver: local}
  odoo-backup: {driver: local}
  odoo-testlogs: {driver: local}
  odoo-dodoo-loader: {driver: local}
  psql: {driver: local}

services:

# ========================

  filebrowser:
    image: filebrowser/filebrowser
    ports: ['8080:80']
    command: ['--noauth']
    volumes:
      - odoo-data:/srv/data
      - odoo-backup:/srv/backup
      - odoo-testlogs:/srv/testlogs
      - odoo-dodoo-loader:/srv/etl

# ========================

  wdb:
    image: xoes/wdb-server
    ports: ['1984:1984']

# ------------------------

  postgres:
    image: 'postgres:alpine'
    # 5432 might be taken by a locally running instance
    ports: ['5433:5432']
    volumes: ['psql:/var/lib/postgresql/data']
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    networks:
      default:
        aliases:
         - db

# ------------------------

  odoo:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    command: []
    depends_on: ['postgres', 'wdb']

# ========================

  scaffold:
    << : *default-odoo
    user: "${COMPOSE_IMPERSONATION}"
    entrypoint: ['/entrypoint.sh', 'scaffold']
    command: []
    volumes:
    - ./src:/opt/odoo/addons/090

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--stop-after-init', '--logfile', '/testlogs/']
    command: []

# ------------------------

  shell:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', 'shell']
    command: []

# ------------------------

  migrate:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', 'migrate-dev-wrapper']
    command: []

# ------------------------

  init:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', 'dodoo', 'init']
    command: []

# ------------------------

  load:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', 'dodoo', 'load']
    command: []

# ------------------------

  apply-patches:
    tty: true  # Do not avoid json logging
    image: "${IMAGE}:devops-${ODOO_VERSION}"
    volumes:
    - ./vendor:/opt/odoo/vendor
    user: "${COMPOSE_IMPERSONATION}"
    entrypoint: ['/patches']
    command: []

# ------------------------

  # translate:
  #   << : *default-odoo
  #   depends_on: ['postgres', 'wdb']
  #   entrypoint: ['/entrypoint.sh', 'translate']
  #   command: []
