version: '3.4'

volumes:
  data: {driver: local}
  psql: {driver: local}

networks:
  default: {internal: true}
  public: null

services:

  db:
    environment: [POSTGRES_USER=odoo, POSTGRES_PASSWORD=odoo, POSTGRES_DB=postgres]
    image: postgres:11-alpine
    volumes: ['psql:/var/lib/postgresql/data']

  # WARNING: Heavily tweak this for production
  # TODO: Kindly provide a PR upstream refactoring this to traeffik
  proxy:
    image: envoyproxy/envoy-alpine:v1.11.2
    networks:
      default:
        aliases:
        # For odoo to reach wkhtml from within the private network
        # Through the proxy: see envoy.yaml
        - odoo.localhost
        # See envoy.yaml
        - cdnjs.cloudflare.com
        - fonts.googleapis.com
        - fonts.gstatic.com
        - www.google.com
        - www.gravatar.com
      public: null
    ports: ['80:80', '9901:9901']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']

  # http://odoo.localhost/longpolling/
  odoo-longpolling:
    image: "${REPO}:${PRODIMAGE}"
    volumes:
    - data:/var/lib/odoo-persist
    entrypoint: ['/entrypoint.sh', 'gevent']
    depends_on: ['db', 'proxy']

  # http://odoo.localhost
  odoo:
    image: "${REPO}:${PRODIMAGE}"
    volumes:
    - data:/var/lib/odoo-persist
    command: ['/entrypoint.sh', 'run']
    depends_on: ['db', 'proxy']
