version: '3.4'


# x-* key is ignored by docker-compose
x-odoo-dev-common:
  &odoo-dev-common
  image: "${REPO}:${DEVOPSIMAGE}"
  tty: true
  volumes:

  # Named Data Volumes
  - data:/var/lib/odoo-persist
  - tests:/var/log/dodoo/tests
  - loader:/var/lib/dodoo/loader

  # Host Path Volumes (Overlays - for debugging and interactive dev)
  -       ./src:${ODOO_SRC}:ro
  -     ./vendor:${ODOO_VENDOR}:ro
  -     ./_mig.d:${MIG_DIR}:ro
  -   ./_patch.d:${PATCH_DIR}:ro
  -  ./odoo.conf:${ODOO_RC}:ro
  - ./pytest.ini:${ODOO_BASEPATH}/pytest.ini:ro
  -       ./odoo:${ODOO_FRM}

  # Example of loading a local python library during development
  # - ~/dev/github.com/xoe-labs/python-xmlsig/src/xmlsig/:/usr/local/lib/python3.7/site-packages/xmlsig/

volumes:
  tests: {driver: local}
  loader: {driver: local}

services:

  db:
    # Do expose during development
    ports: ['5433:5432']
    networks: {public: null}

  odoo:
    << : *odoo-dev-common
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['db', 'wdb', 'proxy']

  odoo-longpolling:
    << : *odoo-dev-common
    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['db', 'wdb', 'proxy']

  # http://filebrowser.localhost
  filebrowser:
    command: [--noauth]
    image: filebrowser/filebrowser
    volumes: ['data:/srv/data', 'tests:/srv/tests',
      'loader:/srv/loader']

  # http://mail.localhost
  smtpfake: {image: mailhog/mailhog}

  # http://wdb.localhost
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']
