.tests:
  image:
    # name: ${FROM}:${FROM_VERSION}-${ODOO_VERSION}-devops  # Set in Gitlab UI !!
    name: xoelabs/dockery-odoo:edge-12.0-devops  # Adapt to image manually !!
    entrypoint: [""]
  except:
    refs: ['/^hotfix\/.*$/', 'schedules']
  stage: Test
  services:
  - postgres:latest
  artifacts:
    paths:
    - logs
    expire_in: 1 week
    when: on_failure
  variables:
    # You can alternatively use an external db connection:
    # Use the CUSTOM_CONFIG variable
    POSTGRES_DB: postgres
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: "odoo"
  before_script:
  # Set the repo's environment
  - export $(egrep -v '^#' .env | xargs)
  - export ODOO_DB_NAME="OdooTest-${CI_COMMIT_TAG:=${CI_PIPELINE_IID}}"
  - pwd  # Orientation
  - ls -la  # Orientation

  # Prepare the runtime environment and construe addons paths
  - export ODOO_BASEPATH="${CI_PROJECT_DIR}"

  # Cleanup and set the logs artifact folder
  - rm -rf "${CI_PROJECT_DIR}/logs" || true
  - mkdir -p "${CI_PROJECT_DIR}/logs" && touch ${CI_PROJECT_DIR}/logs/{init.log,test.log}

  # Apply DockeryOdoo patches from the CI runtime image in case checked-in odoo
  # does not already contain it fail gracefully, if it does.
  - /usr/local/bin/apply-patches.sh /opt/odoo/patches.d "${ODOO_BASEPATH}" || true

  - if [[ -r "${CI_PROJECT_DIR}/.adminpwd" ]]; then export ODOO_ADMINPASSWORD_FILE="${CI_PROJECT_DIR}/.adminpwd"; fi
  - source /entrypoint.d/05-set-appenv-ci.sh
  - source /entrypoint.d/10-set-appenv.sh

  # Apply patches from last commit
  # We just apply all patches again, just in case checked-in odoo
  # does not already contain it: fail gracefully, if it does.
  - /usr/local/bin/apply-patches.sh "${ODOO_BASEPATH}"/patches.d "${ODOO_BASEPATH}" || true

  # Reset custom config and run with **initlogs** file config
  - echo "${CUSTOM_CONFIG}" > "${ODOO_RC}/01-custom.ini"
  - echo "logfile = ${CI_PROJECT_DIR}/logs/init.log" >> "${ODOO_RC}/01-custom.ini"
  - dodoo init -n "${ODOO_DB_NAME}"

  # Reset custom config and run with **testlogs** file config
  - echo "${CUSTOM_CONFIG}" > "${ODOO_RC}/01-custom.ini"
  - echo "logfile = ${CI_PROJECT_DIR}/logs/test.log" >> "${ODOO_RC}/01-custom.ini"
